version: "3.4"
services:

  frontend:
    build: .
    container_name: production-control_frontend
    restart: always
    environment:
      REACT_APP__API_URL: 'http://localhost:5000'
    ports:
      - 3000:80
